"""Vendor mission gateway (P5, D072): authorized high-level tasks to a vendor-managed dock, and what comes back.

The gateway runs inside the mission service and takes a vendor robot's deliveries through the same claim gate as an
onboard uplink (cancel intent, approval expiry, backend, eligibility and reservation re-checked in one transaction).
It verifies the approval signature like the aircraft would, recomputes the vendor task from the approved package and
refuses any task whose digest differs from the one pinned at admission. Each command's transaction id depends only on
(flight, command), so a resend after a lost reply, a broken link or a restart can never start a second execution.

Everything the gateway sends and receives is written as a hash-chained `vendor` journal (the same row format as the
onboard journals, generated by the gateway and labelled as such, never presented as an executive or guardian log);
the service derives each version's state from it. Progress only moves forward by the vendor's sequence number, a
terminal status is never overwritten, duplicates are journaled once. An acknowledgement is receipt; completion needs
the terminal progress and service-verified media; landing needs the vendor's dock state after the terminal. The
vendor's dock state becomes a P1 dock report under the dock's bound identity and its aircraft state a robot status.

厂商任务网关（P5，D072）：把已授权的高层任务交给厂商托管机场，并核对其回报。

网关运行在任务服务内，像机载 uplink 一样经同一领取闸门领取厂商机器人的投递（取消意图、审批有效期、后端、可派遣判定与预约
在一个事务内重查）。它像飞行器一样验证审批签名，由已批准任务包重新推导厂商任务，摘要与准入时固定的不一致即拒绝。每个命令的
事务 ID 只取决于（飞行，命令），因此丢失答复、断线或重启之后的重发永远不会开始第二次执行。

网关发送与收到的一切都写成哈希链的 `vendor` 账本（与机载账本同一行格式，由网关生成并如实标注，从不冒充 executive 或
guardian 日志）；服务据此派生每个版本的状态。进度按厂商序号只前进，终态从不被覆盖，重复报文只入账一次。ACK 只是受理；完成
需要终态进度与服务复核过的媒体；落地需要终态之后的厂商机场状态。厂商机场状态以该机场绑定的身份成为 P1 机场报告，其飞行器
状态成为机器人状态。
"""

from __future__ import annotations

import asyncio
import base64
import contextlib
import hashlib
import json
import re
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

from drone_agent.contracts import (
    CommsState,
    EffectVerdict,
    EnergyState,
    Evidence,
    ExecutionStatus,
    Frame,
    LocalizationHealth,
    MissionPackage,
    Pose,
    Position,
    RobotStatus,
    StepOutcome,
    TimeWindow,
    utcnow,
)
from drone_agent.fleet.events import event_to_row, journal_row_to_event, verify_chain
from drone_agent.fleet.provenance import NAMESPACE, unseal
from drone_agent.fleet.transport import RAW_RGB
from drone_agent.fleet.vendor import TERMINAL, VendorError, VendorTask, check_inbound, command, compile_task
from drone_agent.runtime.ledger import content_hash
from drone_agent.runtime.signing import SignatureRejected, TrustStore, verify_package

JOURNAL = "vendor"
SEALED_TASK = "vendor_task"
BOOT = re.compile(r"[^A-Za-z0-9_-]")
# Terminal statuses that never involved a flight (nothing physical happened). / 从未飞行的终态（没有任何物理动作）。
GROUND_ONLY = ("unreachable", "undone", "prepare_rejected", "execute_rejected")


def sealed_task(record: dict) -> VendorTask | None:
    """The vendor task pinned at admission, or None for a version without one. / 准入时固定的厂商任务。"""
    saved = ((record or {}).get("decision") or {}).get(NAMESPACE, {})
    return unseal(saved[SEALED_TASK], VendorTask) if SEALED_TASK in saved else None


# ── the journal summary the service derives state from / 服务据以派生状态的账本摘要 ──


@dataclass
class Summary:
    """What a vendor journal says about one version; a pure function of its rows. / 一个版本的厂商账本所述内容；行的纯函数。"""

    task_sha256: str | None = None
    flight_id: str | None = None
    delivery_id: str | None = None
    sent: dict[str, dict] = field(default_factory=dict)  # method -> {"first", "last", "attempts"}
    replies: dict[str, dict] = field(default_factory=dict)  # method -> {"result", "output", "at"}
    seen: set[tuple[str, int]] = field(default_factory=set)
    applied_seq: int = -1
    status: str | None = None
    reached: int = 0
    progressed: bool = False
    terminal: dict | None = None  # {"status", "at", "physical"}
    grounded_at: str | None = None
    media: dict[int, dict] = field(default_factory=dict)
    media_missing: bool = False
    cancel: dict | None = None
    refused: str | None = None
    link: str = "up"

    @property
    def executing(self) -> bool:
        return self.progressed or self.replies.get("flighttask_execute", {}).get("result") == 0

    def as_view(self) -> dict:
        return {"flight_id": self.flight_id, "task_sha256": self.task_sha256, "status": self.status,
                "reached": self.reached, "terminal": self.terminal, "grounded_at": self.grounded_at,
                "media": {str(k): v for k, v in sorted(self.media.items())}, "media_missing": self.media_missing,
                "cancel": self.cancel, "refused": self.refused, "link": self.link,
                "commands": {m: {**s, "reply": self.replies.get(m, {}).get("result")} for m, s in self.sent.items()}}


def summarize(rows: list[dict]) -> Summary:
    """Fold the rows of one version's vendor journal. / 折叠一个版本厂商账本的各行。"""
    s = Summary()
    for row in sorted(rows, key=lambda r: r["seq"]):
        kind, data, at = row["kind"], row["data"], row["timestamp"]
        if kind == "task":
            s.task_sha256, s.flight_id, s.delivery_id = data["task_sha256"], data["flight_id"], data["delivery_id"]
        elif kind == "command":
            sent = s.sent.setdefault(data["method"], {"first": at, "last": at, "attempts": 0})
            sent["last"], sent["attempts"] = at, sent["attempts"] + 1
        elif kind == "reply":
            s.replies.setdefault(data["method"], {"result": data["result"], "output": data.get("output"), "at": at})
        elif kind == "event":
            s.seen.add((data["method"], data["seq"]))
            if data["method"] == "flighttask_progress":
                s.progressed = s.progressed or data.get("status") not in (None, "sent")
                if data.get("applied"):
                    s.applied_seq = max(s.applied_seq, data["seq"])
                    s.status = data.get("status")
                    s.reached = max(s.reached, int(data.get("current_step") or 0))
        elif kind == "terminal":
            if s.terminal is None:
                s.terminal = {"status": data["status"], "at": at, "physical": data["physical"]}
        elif kind == "grounded":
            s.grounded_at = s.grounded_at or at
        elif kind == "media":
            s.media[int(data["step_index"])] = {k: data[k] for k in ("evidence_id", "sha256", "accepted", "reason")}
        elif kind == "media_missing":
            s.media_missing = True
        elif kind == "cancel":
            s.cancel = s.cancel or {"via": data["via"], "request_id": data["request_id"], "at": at}
        elif kind == "refused":
            s.refused = s.refused or data["reason"]
        elif kind == "link":
            s.link = data["state"]
    return s


def vendor_outcomes(task: VendorTask, summary: Summary, robot_id: str,
                    verdicts: dict[str, EffectVerdict]) -> dict[str, StepOutcome]:
    """Per package node: execution from the vendor's progress, effect only from service-verified media.

    A node the vendor has not started has no outcome, so the report lists it as not run. A step is succeeded once the vendor's applied progress moved past all of its waypoints (or the task ended ok); the
    inspection's effect is the service's verdict on the vendor's media and every other effect is unknown, because the
    platform cannot observe it. The safety verdict field keeps its default only because the contract has no
    'not observable' value; it is never shown or used for vendor tasks, whose safety is the vendor's (D072).

    按任务包节点：执行状态来自厂商进度，效果只来自服务复核过的媒体。厂商尚未开始的节点没有结果，报告因此列为未执行。厂商已应用的进度越过某步全部航点（或任务以 ok 结束）即该步
    成功；巡检的效果是服务对厂商媒体的判定，其余效果为 unknown，因为平台观测不到。安全判定字段只因契约没有「不可观测」取值而保留
    缺省值；厂商任务从不展示或使用它，其安全由厂商负责（D072）。
    """
    reached = len(task.steps) if summary.terminal and summary.terminal["status"] == "ok" else summary.reached
    end = summary.terminal["status"] if summary.terminal else None
    found = {}
    for node, steps in task.nodes().items():
        last = max(step.index for step in steps)
        if last < reached:
            status = ExecutionStatus.SUCCEEDED
        elif end == "canceled" or end == "undone":
            status = ExecutionStatus.CANCELLED
        elif end in ("failed", "partially_done", "rejected", "prepare_rejected", "execute_rejected", "unreachable"):
            status = ExecutionStatus.FAILED
        elif end == "timeout":
            status = ExecutionStatus.TIMEOUT
        elif summary.executing:
            status = ExecutionStatus.RUNNING
        else:
            continue  # not started: the report says not run, as for an onboard flight / 未开始：报告为未执行，与机载飞行相同
        photo = any(step.kind == "photo" for step in steps)
        effect = verdicts.get(node, EffectVerdict.UNKNOWN) if photo else EffectVerdict.UNKNOWN
        found[node] = StepOutcome(mission_id=task.mission_id, mission_version=task.mission_version, step_id=node,
                                  robot_id=robot_id, execution_status=status, effect_verdict=effect)
    return found


# ── links / 链路 ──


class SocketLink:
    """JSON lines over a Unix socket to the vendor endpoint, reconnecting with a back-off.

    经 Unix 套接字以 JSON 行连接厂商端点，断开后退避重连。
    """

    def __init__(self, path: Path, *, retry_s: float = 2.0):
        self.path, self.retry_s = path, retry_s
        self.reader = self.writer = None
        self.inbox: list[dict] = []
        self.retry_at = 0.0
        self.task: asyncio.Task | None = None

    @property
    def connected(self) -> bool:
        return self.writer is not None and not self.writer.is_closing()

    async def ensure(self) -> bool:
        if self.connected:
            return True
        if time.monotonic() < self.retry_at:
            return False
        self.retry_at = time.monotonic() + self.retry_s
        try:
            self.reader, self.writer = await asyncio.open_unix_connection(str(self.path), limit=8 * 1024 * 1024)
        except OSError:
            self.reader = self.writer = None
            return False
        self.task = asyncio.create_task(self._read())
        return True

    async def _read(self) -> None:
        reader = self.reader
        try:
            while True:
                line = await reader.readline()
                if not line:
                    break
                with contextlib.suppress(ValueError):
                    self.inbox.append(json.loads(line))
        except (OSError, asyncio.LimitOverrunError, ValueError):
            pass
        finally:
            await self.close()

    async def send(self, message: dict) -> bool:
        if not self.connected:
            return False
        try:
            self.writer.write(json.dumps(message, ensure_ascii=False).encode() + b"\n")
            await self.writer.drain()
            return True
        except OSError:
            await self.close()
            return False

    def drain(self) -> list[dict]:
        items, self.inbox = self.inbox, []
        return items

    async def close(self) -> None:
        writer, self.writer = self.writer, None
        if writer is not None:
            writer.close()
            with contextlib.suppress(OSError, ConnectionError):
                await writer.wait_closed()


# ── the gateway / 网关 ──


@dataclass
class Task:
    """One claimed vendor task: its journal rows and the summary they fold to. / 一个已领取的厂商任务。"""

    mission_id: str
    version: int
    robot_id: str
    dock_id: str
    task: VendorTask | None
    rows: list[dict] = field(default_factory=list)
    summary: Summary = field(default_factory=Summary)

    @property
    def key(self) -> tuple[str, int]:
        return self.mission_id, self.version

    def done(self) -> bool:
        s = self.summary
        if s.refused and s.terminal is None:
            return True
        if s.terminal is None:
            return False
        if s.terminal["physical"] and s.grounded_at is None:
            return False
        photo_ok = s.terminal["status"] != "ok" or s.media_missing or any(m["accepted"] for m in s.media.values())
        return photo_ok


class VendorGateway:
    """In-process gateway for every vendor-managed dock of the catalog. / 目录中全部厂商托管机场的进程内网关。"""

    def __init__(self, service, links: dict, *, clock=utcnow):
        self.service, self.links, self.clock = service, links, clock
        self.ledger, self.hub, self.ops = service.ledger, service.hub, service.ops
        catalog = self.ops.catalog
        self.docks = {dock_id: entry for dock_id, entry in catalog.docks.items() if entry.vendor_managed}
        self.robots = {robot_id: entry.dock_id for robot_id, entry in catalog.robots.items()
                       if entry.dock_id in self.docks}
        missing = set(self.docks) - set(links)
        if missing:
            raise ValueError(f"no vendor link for {', '.join(sorted(missing))}")
        self.trust = TrustStore.from_entries([service.key.trust_entry()])
        self.tasks: dict[tuple[str, int], Task] = {}
        self.tids: dict[str, tuple[tuple[str, int], str]] = {}
        self.boots: dict[str, str] = {}
        self.up: dict[str, bool] = dict.fromkeys(self.docks, False)
        self.state_seq: dict[str, int] = {}
        self.touched: set[str] = set()
        self.loaded = False
        self.counts = {"rejected_messages": 0, "duplicates": 0, "unknown_flight": 0}

    # ── journal / 账本 ──

    def _append(self, task: Task, kind: str, data: dict) -> dict:
        body = {"seq": len(task.rows), "previous": task.rows[-1]["sha256"] if task.rows else "0" * 64,
                "timestamp": self.clock().isoformat(), "monotonic_ns": time.monotonic_ns(), "kind": kind, "data": data}
        row = {**body, "sha256": content_hash(body)}
        event = journal_row_to_event(row, journal=JOURNAL, robot_id=task.robot_id, mission_id=task.mission_id,
                                     version=task.version)
        if not self.ledger.record_event(task.robot_id, event):
            raise RuntimeError(f"vendor journal row {row['seq']} of {task.mission_id} already exists")
        task.rows.append(row)
        task.summary = summarize(task.rows)
        self.touched.add(task.mission_id)
        return row

    def _load(self) -> None:
        """Rebuild unfinished tasks from the ledger after a start or a restart. / 启动或重启后从账本重建未结束的任务。"""
        grouped: dict[tuple[str, int, str], list[dict]] = {}
        for row in self.ledger._rows("SELECT robot_id, mission_id, mission_version, body FROM events "
                                     "WHERE journal=? ORDER BY mission_id, mission_version, seq", (JOURNAL,)):
            grouped.setdefault((row["mission_id"], row["mission_version"], row["robot_id"]), []).append(
                event_to_row(json.loads(row["body"])))
        for (mission_id, version, robot_id), rows in grouped.items():
            if robot_id not in self.robots or not verify_chain(rows)[0]:
                continue
            record = self.ledger.version(mission_id, version)
            task = Task(mission_id, version, robot_id, self.robots[robot_id], sealed_task(record), rows=rows,
                        summary=summarize(rows))
            if not task.done():
                self._index(task)
        self.loaded = True

    def _index(self, task: Task) -> None:
        self.tasks[task.key] = task
        if task.task is not None:
            from drone_agent.fleet.vendor import transaction_id

            for method in ("flighttask_prepare", "flighttask_execute", "flighttask_undo", "return_home"):
                self.tids[transaction_id(task.task.flight_id, method)] = (task.key, method)

    # ── the tick / 一次处理 ──

    async def tick(self) -> set[str]:
        if not self.loaded:
            self._load()
        for dock_id, link in self.links.items():
            if dock_id not in self.docks:
                continue
            connected = await link.ensure()
            if not connected and self.up.get(dock_id):
                self.up[dock_id] = False
                for task in self._of_dock(dock_id):
                    self._append(task, "link", {"state": "down", "boot_id": self.boots.get(dock_id)})
            for message in link.drain():
                self._inbound(dock_id, message)
        await self._pull()
        await self._advance()
        touched, self.touched = self.touched, set()
        return touched

    def _of_dock(self, dock_id: str) -> list[Task]:
        return [task for task in self.tasks.values() if task.dock_id == dock_id]

    # ── inbound / 入站 ──

    def _inbound(self, dock_id: str, message) -> None:
        try:
            message = check_inbound(message)
        except VendorError:
            self.counts["rejected_messages"] += 1
            return
        kind = message["kind"]
        if kind == "hello":
            boot = BOOT.sub("", str(message["boot_id"]))[:64]
            profile = self.ops.profiles[dock_id][0]
            if message["protocol"] != f"{profile.protocol.name}/{profile.protocol.version}" or len(boot) < 8:
                self.counts["rejected_messages"] += 1
                return
            replaced = self.boots.get(dock_id) not in (None, boot)
            self.boots[dock_id] = boot
            if replaced:
                self.state_seq.pop(dock_id, None)
            if not self.up.get(dock_id):
                self.up[dock_id] = True
                for task in self._of_dock(dock_id):
                    self._append(task, "link", {"state": "up", "boot_id": boot})
            return
        if kind == "state":
            self._state(dock_id, message)
            return
        if kind == "service_reply":
            found = self.tids.get(message["tid"])
            if found is None or found[0] not in self.tasks:
                self.counts["unknown_flight"] += 1
                return
            self._reply(self.tasks[found[0]], found[1], message)
            return
        task = next((t for t in self.tasks.values() if t.task and t.task.flight_id == message["bid"]), None)
        if task is None:
            self.counts["unknown_flight"] += 1
            return
        self._event(task, message)

    def _reply(self, task: Task, method: str, message: dict) -> None:
        if message.get("method") != method or method in task.summary.replies:
            self.counts["duplicates"] += 1
            return
        result = int(message["data"]["result"])
        output = message["data"].get("output") if isinstance(message["data"].get("output"), dict) else None
        self._append(task, "reply", {"method": method, "tid": message["tid"], "result": result,
                                     "output": output})
        s = task.summary
        if method == "flighttask_prepare" and result != 0 and s.terminal is None:
            self._append(task, "terminal", {"status": "prepare_rejected", "physical": False, "result": result})
        elif method == "flighttask_execute" and result != 0 and not s.progressed and s.terminal is None:
            # Refused before any progress: the vendor never flew it. / 在任何进度之前被拒：厂商从未执行。
            self._append(task, "terminal", {"status": "execute_rejected", "physical": False, "result": result})
        elif method == "flighttask_undo" and not s.executing and s.terminal is None and \
                (result == 0 or "flighttask_execute" not in s.sent):
            # Undone, or never executable: execute never went out, so whatever the vendor holds cannot fly.
            # 已撤销，或从未可执行：执行命令从未发出，厂商持有的任何内容都不能起飞。
            self._append(task, "terminal", {"status": "undone", "physical": False, "result": result})

    def _event(self, task: Task, message: dict) -> None:
        method, seq, data = message["method"], message["seq"], message["data"]
        s = task.summary
        if (method, seq) in s.seen:
            self.counts["duplicates"] += 1
            return
        if method == "flighttask_progress":
            status = data.get("status")
            if status not in ("sent", "in_progress", "paused", *TERMINAL):
                self.counts["rejected_messages"] += 1
                return
            applied = seq > s.applied_seq and s.terminal is None
            step = data.get("current_step")
            self._append(task, "event", {"method": method, "seq": seq, "status": status,
                                         "current_step": int(step) if isinstance(step, int) else 0,
                                         "percent": data.get("percent"), "applied": applied})
            if applied and status in TERMINAL:
                self._append(task, "terminal", {"status": status, "physical": True, "seq": seq})
        elif method == "file_upload_callback":
            self._append(task, "event", {"method": method, "seq": seq, "step_index": data.get("step_index"),
                                         "sha256": data.get("sha256")})
            self._media(task, data)
        elif method == "return_home_info":
            self._append(task, "event", {"method": method, "seq": seq, "state": str(data.get("state", ""))[:40]})
        else:
            self.counts["rejected_messages"] += 1

    def _media(self, task: Task, data: dict) -> None:
        """Vendor media becomes evidence only if it is whole and names this task's photo step.

        厂商媒体只有完整且指明本任务拍照步骤时才成为证据。
        """
        def refuse(reason: str) -> None:
            self._append(task, "media", {"step_index": data.get("step_index", -1), "evidence_id": None,
                                         "sha256": data.get("sha256"), "accepted": False, "reason": reason})

        steps = {step.index: step for step in task.task.steps} if task.task else {}
        step = steps.get(data.get("step_index"))
        if step is None or step.kind != "photo":
            return refuse("vendor.media_step_unknown")
        try:
            raw = base64.b64decode(str(data.get("media_b64", "")), validate=True)
            width, height = int(data["width"]), int(data["height"])
            captured = datetime.fromisoformat(str(data["captured_at"]))
            pose = data["pose"]
            position = Position(x=float(pose["x"]), y=float(pose["y"]), z=float(pose["z"]),
                                covariance=tuple(float(v) for v in pose["covariance"]))
            frame = Frame(**{k: str(data["frame"][k]) for k in ("frame_id", "map_version")})
        except (KeyError, TypeError, ValueError):
            return refuse("vendor.media_malformed")
        digest = hashlib.sha256(raw).hexdigest()
        if digest != data.get("sha256") or data.get("media_type") != RAW_RGB or len(raw) != width * height * 3:
            return refuse("vendor.media_digest_mismatch")
        evidence = Evidence(evidence_id=f"vendor:{task.task.flight_id}:{step.index}", kind="image",
                            media_ref=str(data.get("object_key", ""))[:200] or f"vendor/{digest}", sha256=digest,
                            time_window=TimeWindow(timestamp=captured, valid_until=captured + timedelta(seconds=0.2)),
                            captured_pose=Pose(frame=frame, position=position), subject_ids=[step.asset_id],
                            quality={"width": width, "height": height}, produced_by_skill_instance=step.node,
                            mission_id=task.mission_id, mission_version=task.version, robot_id=task.robot_id)
        receipt = self.hub.publish_evidence(task.robot_id, evidence)
        if receipt.accepted:
            receipt = self.hub.publish_media(task.robot_id, {
                "mission_id": task.mission_id, "evidence_id": evidence.evidence_id, "robot_id": task.robot_id,
                "data": raw, "sha256": digest, "width": width, "height": height, "media_type": RAW_RGB})
        self._append(task, "media", {"step_index": step.index, "evidence_id": evidence.evidence_id, "sha256": digest,
                                     "accepted": receipt.accepted, "reason": receipt.reason})

    def _state(self, dock_id: str, message: dict) -> None:
        """Dock state as a P1 report under the bound identity; aircraft state as a robot status.

        机场状态以绑定身份成为 P1 报告；飞行器状态成为机器人状态。
        """
        data, seq = message["data"], message["seq"]
        boot = self.boots.get(dock_id)
        if boot is None or seq <= self.state_seq.get(dock_id, -1):
            return
        self.state_seq[dock_id] = seq
        dock, aircraft = data.get("dock") or {}, data.get("aircraft") or {}
        try:
            observed = datetime.fromisoformat(message["ts"])
            charge = float(dock["charge_fraction"])
            charging = bool(dock["charging"])
            report = {"dock_id": dock_id, "boot_id": boot, "seq": seq, "observed_at": observed.isoformat(),
                      "link": "online", "lid": str(dock["lid"]),
                      "aircraft": "present" if dock["aircraft_in_dock"] is True else "absent",
                      "energy": {"state": "charging" if charging else "ready" if charge >= 0.98 else "idle",
                                 "charge_fraction": round(charge, 4)},
                      "environment": {"state": str(dock["environment"]), "wind_mps": float(dock["wind_mps"])},
                      "upkeep": str(dock["upkeep"]), "actions": []}
            phase = "airborne" if aircraft["flight_phase"] == "airborne" else "grounded"
            position = [float(v) for v in aircraft["position"]]
            battery = float(aircraft["battery"])
        except (KeyError, TypeError, ValueError):
            self.counts["rejected_messages"] += 1
            return
        principal = self.docks[dock_id].backend.principal
        self.service.dock_report(principal, report)
        robot_id = self.docks[dock_id].serves[0]
        status = RobotStatus(robot_id=robot_id, timestamp=observed, flight_phase=phase,
                             energy=EnergyState(remaining_fraction=min(1.0, max(0.0, battery))),
                             localization=LocalizationHealth(fix_type="vendor_reported", healthy=True),
                             comms=CommsState(uplink_ok=True, last_seen=observed))
        self.hub.publish_status(robot_id, status)
        for task in self._of_dock(dock_id):
            s = task.summary
            if s.terminal and s.terminal["physical"] and s.grounded_at is None and phase == "grounded" and \
                    dock["aircraft_in_dock"] is True and observed >= datetime.fromisoformat(s.terminal["at"]):
                self._append(task, "grounded", {"seq": seq, "position": position})

    # ── deliveries / 投递 ──

    async def _pull(self) -> None:
        for robot_id in self.robots:
            batch = self.hub.fetch_deliveries(robot_id, robot_id, 0, 10)
            for item in batch["items"]:
                if item["kind"] != "mission_package":
                    # A vendor dock takes no operator requests; cancels go through the persisted intent.
                    # 厂商机场不接收操作请求；取消经持久化的取消意图进行。
                    self.hub.acknowledge(robot_id, robot_id, item["delivery_id"], False, "vendor.action_unsupported")
                    continue
                await self._claim(robot_id, item)

    async def _claim(self, robot_id: str, item: dict) -> None:
        package: MissionPackage = item["package"]
        key = (package.mission_id, package.mission_version)
        if key in self.tasks:
            return
        dock_id = self.robots[robot_id]
        record = self.ledger.version(*key)
        reason = None
        try:
            verify_package(package, self.trust, robot_id=robot_id, now=self.clock())
            pinned = sealed_task(record)
            profile, profile_sha = self.ops.profiles[dock_id]
            fresh = compile_task(package, self.ops.registry(robot_id), profile, profile_sha, robot_id=robot_id,
                                 dock_id=dock_id)
            if pinned is None or fresh.sha256 != pinned.sha256:
                reason = "vendor.task_mismatch"
        except SignatureRejected as error:
            reason = error.code
        except (VendorError, KeyError, ValueError) as error:
            reason = "vendor.task_mismatch" if isinstance(error, VendorError) else "service.invalid_request"
        if reason is not None:
            self.hub.acknowledge(robot_id, robot_id, item["delivery_id"], False, reason)
            self.touched.add(package.mission_id)
            return
        task = Task(package.mission_id, package.mission_version, robot_id, dock_id, pinned)
        self._index(task)
        self._append(task, "task", {"flight_id": pinned.flight_id, "task_sha256": pinned.sha256,
                                    "profile_sha256": pinned.profile_sha256, "delivery_id": item["delivery_id"]})
        self.hub.acknowledge(robot_id, robot_id, item["delivery_id"], True, "vendor.claimed")
        await self._send(task, "flighttask_prepare", pinned.wire())

    # ── commands / 命令 ──

    async def _send(self, task: Task, method: str, data: dict) -> None:
        """Journal the command first, then send it: after a crash the journal says it may have gone out.

        先记账再发送：崩溃之后账本表明它可能已经发出。
        """
        message = command(method, flight=task.task.flight_id, gateway=task.dock_id, data=data,
                          ts=self.clock().isoformat())
        self._append(task, "command", {"method": method, "tid": message["tid"]})
        await self.links[task.dock_id].send(message)

    async def _advance(self) -> None:
        now = self.clock()
        for task in list(self.tasks.values()):
            if task.done():
                self.tasks.pop(task.key, None)
                continue
            s = task.summary
            profile = self.ops.profiles[task.dock_id][0]
            intent = self.ops.store.cancel_intent(task.mission_id) if s.terminal is None and s.cancel is None else None
            if intent is not None:
                # Before execute went out an undo is enough; once it may have, return home, and while nothing
                # answered yet also undo, so a still-prepared task can never start (D072).
                # 执行命令发出之前撤销即可；一旦可能已发出就返航，尚无任何答复时同时撤销，使仍处于准备状态的任务永远不会开始（D072）。
                if "flighttask_execute" not in s.sent:
                    vias = ["flighttask_undo"]
                elif s.executing:
                    vias = ["return_home"]
                else:
                    vias = ["return_home", "flighttask_undo"]
                self._append(task, "cancel", {"via": "+".join(vias), "request_id": intent["request_id"]})
                for via in vias:
                    await self._send(task, via, {"flight_id": task.task.flight_id})
                continue
            if s.terminal is None:
                await self._resend(task, profile, now)
                s = task.summary
                prepared = s.replies.get("flighttask_prepare", {}).get("result") == 0
                if prepared and s.cancel is None and "flighttask_execute" not in s.sent:
                    await self._send(task, "flighttask_execute", {"flight_id": task.task.flight_id})
            elif s.terminal["status"] == "ok" and not s.media_missing and \
                    not any(m["accepted"] for m in s.media.values()) and \
                    (now - datetime.fromisoformat(s.terminal["at"])).total_seconds() > profile.media_grace_s:
                self._append(task, "media_missing", {"grace_s": profile.media_grace_s})

    async def _resend(self, task: Task, profile, now: datetime) -> None:
        """Resend unanswered commands with the same transaction; give up only where nothing could have flown.

        以同一事务重发未答复的命令；只在不可能已经起飞的情况下放弃。
        """
        s = task.summary
        roles = {spec.method: spec for spec in profile.commands.values()}
        for method, sent in list(s.sent.items()):
            if method in s.replies or (method == "flighttask_execute" and s.progressed):
                continue
            if s.cancel is not None and method in ("flighttask_prepare", "flighttask_execute"):
                continue  # never push a cancelled task forward / 已取消的任务绝不再向前推进
            spec = roles[method]
            since = (now - datetime.fromisoformat(sent["first"])).total_seconds()
            last = (now - datetime.fromisoformat(sent["last"])).total_seconds()
            if since > spec.give_up_s:
                if method in ("flighttask_prepare", "flighttask_undo") and "flighttask_execute" not in s.sent \
                        and task.summary.terminal is None:
                    status = "undone" if method == "flighttask_undo" else "unreachable"
                    self._append(task, "terminal", {"status": status, "physical": False, "gave_up": method})
                continue
            if last >= spec.resend_s and self.links[task.dock_id].connected:
                data = task.task.wire() if method == "flighttask_prepare" else {"flight_id": task.task.flight_id}
                await self._send(task, method, data)

    # ── what the service asks / 服务的查询 ──

    def view(self, mission_id: str, version: int) -> dict | None:
        task = self.tasks.get((mission_id, version))
        return task.summary.as_view() if task else None
