"""RecoveryPolicy: the platform-specific graph of verified baseline behaviours.

Nodes are baseline behaviours (Simplex "verified controller" set), edges are trigger x context
guards. The policy is scenario configuration (YAML), never generated by an LLM. Every edge needs
a passed injection record bound to its definition before it may enter a production config.

RecoveryPolicy：平台专用的已验证基线行为图。

节点是基线行为（Simplex 架构中的「已验证控制器」集合），边是触发条件 × 上下文守卫。
策略是场景配置（YAML），不由 LLM 生成。每条边在进入生产配置前，必须具备与其定义
绑定的故障注入通过记录。
"""

from __future__ import annotations

import hashlib
import json
from enum import StrEnum
from pathlib import Path
from typing import Any

import yaml
from pydantic import AwareDatetime, Field, model_validator

from drone_agent.contracts.capability import CapabilityDescriptor, RecoveryBehavior
from drone_agent.contracts.common import ContractModel, Embodiment


class RecoveryTrigger(StrEnum):
    """Conditions that can move control to a baseline behaviour. / 可把控制切到基线行为的触发条件。"""

    EXECUTIVE_HEARTBEAT_LOST = "executive_heartbeat_lost"
    OBSERVATION_STALE = "observation_stale"
    TRAJECTORY_STALE = "trajectory_stale"
    LEASE_EXPIRED = "lease_expired"
    ENERGY_LOW = "energy_low"
    GEOFENCE_PREDICTED_BREACH = "geofence_predicted_breach"
    LOCALIZATION_DEGRADED = "localization_degraded"
    UPLINK_LOST = "uplink_lost"
    FC_FAILSAFE_ACTIVE = "fc_failsafe_active"
    USER_PAUSE = "user_pause"
    USER_CANCEL = "user_cancel"
    # M3 (D042): appended; the order is wire-significant. / M3（D042）：追加；顺序影响 wire 编号。
    PROGRESS_STALLED = "progress_stalled"
    COMPUTE_OVERLOADED = "compute_overloaded"
    AUTONOMY_UNAVAILABLE = "autonomy_unavailable"


class RecoveryValidation(ContractModel):
    """Evidence of a passed injection run, bound to one exact edge.

    绑定到一条确切策略边的故障注入通过记录。
    """

    scenario_id: str = Field(min_length=1)
    edge_hash: str = Field(pattern=r"^[0-9a-f]{64}$")
    software_revision: str = Field(min_length=1)
    tested_at: AwareDatetime
    evidence_ref: str = Field(min_length=1)


class RecoveryEdge(ContractModel):
    """One trigger x guard -> behaviour rule, optionally followed by a second behaviour after a delay.

    一条「触发条件 × 守卫 → 行为」规则，可选在延迟后接第二个行为。
    """

    trigger: RecoveryTrigger
    guard: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "context predicates: list value = membership, scalar = equality; missing key = no match / "
            "上下文谓词：列表值表示属于，标量表示相等；上下文缺键即不匹配"
        ),
    )
    target: RecoveryBehavior
    then: RecoveryBehavior | None = Field(
        default=None, description="follow-up behaviour after `after_s` / 经过 `after_s` 后接续的行为"
    )
    after_s: float | None = Field(default=None, gt=0)
    fault_injection_scenario: str | None = Field(
        default=None, description="planned injection scenario; not proof of validation / 计划中的注入场景，不是验证证据"
    )
    validation: RecoveryValidation | None = None

    def validation_hash(self) -> str:
        """Hash the edge definition without its validation record.

        对不含验证记录的策略边定义计算哈希。
        """
        payload = self.model_dump(mode="json", exclude={"validation"})
        canonical = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    @property
    def is_verified(self) -> bool:
        """A scenario name alone never proves this edge was tested.

        仅有场景名永远不能证明该边经过了验证。
        """
        return (
            self.validation is not None
            and self.validation.scenario_id == self.fault_injection_scenario
            and self.validation.edge_hash == self.validation_hash()
        )

    @model_validator(mode="after")
    def _then_needs_delay(self) -> RecoveryEdge:
        if (self.then is None) != (self.after_s is None):
            raise ValueError("`then` and `after_s` must be given together")
        return self

    def matches(self, trigger: RecoveryTrigger, context: dict[str, Any]) -> bool:
        """Trigger must equal and every guard key must be present and satisfied.

        触发条件必须相等，且每个守卫键都必须存在并满足。
        """
        if trigger is not self.trigger:
            return False
        for key, expected in self.guard.items():
            if key not in context:
                return False
            actual = context[key]
            if isinstance(expected, list):
                if actual not in expected:
                    return False
            elif actual != expected:
                return False
        return True


class RecoveryPolicy(ContractModel):
    """The whole graph for one embodiment, plus the conditions to resume the high-performance path.

    某一本体的完整策略图，以及切回高性能路径的条件。
    """

    policy_id: str
    version: str
    embodiment: Embodiment
    nodes: set[RecoveryBehavior]
    edges: list[RecoveryEdge]
    resume_conditions: list[str] = Field(
        default_factory=list,
        description=(
            "all must hold before control returns to the high-performance path / "
            "全部成立后才允许把控制交还高性能路径"
        ),
    )

    @model_validator(mode="after")
    def _edges_reference_nodes(self) -> RecoveryPolicy:
        for e in self.edges:
            for b in (e.target, e.then):
                if b is not None and b not in self.nodes:
                    raise ValueError(f"edge for {e.trigger.value} targets {b.value}, which is not a policy node")
        return self

    def validate_against(self, caps: CapabilityDescriptor) -> list[str]:
        """Errors that make this policy unusable on the given platform.

        使该策略在给定平台上不可用的错误列表。
        """
        errors: list[str] = []
        if caps.embodiment is not self.embodiment:
            errors.append(f"embodiment mismatch: policy {self.embodiment.value}, robot {caps.embodiment.value}")
        unsupported = sorted(b.value for b in self.nodes if b not in caps.recovery_behaviors)
        if unsupported:
            errors.append(f"behaviours not supported by platform: {unsupported}")
        if not caps.limits.can_hover and RecoveryBehavior.HOLD in self.nodes:
            errors.append("platform cannot hover; use loiter instead of hold")
        return errors

    def unverified_edges(self) -> list[RecoveryEdge]:
        """Edges without passed evidence bound to their current content.

        没有与当前内容绑定的通过证据的策略边。
        """
        return [e for e in self.edges if not e.is_verified]

    def require_verified(self) -> None:
        """Reject production use until every edge has matching validation evidence.

        所有策略边具有匹配的验证证据前拒绝生产使用。
        """
        if self.unverified_edges():
            raise ValueError("recovery policy contains unverified edges")

    def select(self, trigger: RecoveryTrigger, context: dict[str, Any]) -> RecoveryEdge | None:
        """First matching edge wins; order edges from most specific to least specific.

        首个匹配的边生效；边应从最具体到最一般排列。
        """
        for e in self.edges:
            if e.matches(trigger, context):
                return e
        return None

    @classmethod
    def from_yaml(cls, path: str | Path) -> RecoveryPolicy:
        """Load and validate a policy file. / 加载并校验策略文件。"""
        data = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        return cls.model_validate(data)
