"""RecoveryPolicy: the platform-specific graph of verified baseline behaviours.

Nodes are baseline behaviours (Simplex "verified controller" set), edges are trigger x context
guards. The policy is scenario configuration (YAML), never generated by an LLM. Every edge must
name the fault-injection scenario that verified it before it may enter a production config.
"""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path
from typing import Any

import yaml
from pydantic import Field, model_validator

from drone_agent.contracts.capability import CapabilityDescriptor, RecoveryBehavior
from drone_agent.contracts.common import ContractModel, Embodiment


class RecoveryTrigger(StrEnum):
    EXECUTIVE_HEARTBEAT_LOST = "executive_heartbeat_lost"
    OBSERVATION_STALE = "observation_stale"
    TRAJECTORY_STALE = "trajectory_stale"
    LEASE_EXPIRED = "lease_expired"
    ENERGY_LOW = "energy_low"
    GEOFENCE_PREDICTED_BREACH = "geofence_predicted_breach"
    LOCALIZATION_DEGRADED = "localization_degraded"
    UPLINK_LOST = "uplink_lost"
    FC_FAILSAFE_ACTIVE = "fc_failsafe_active"
    USER_PAUSE = "user_pause"
    USER_CANCEL = "user_cancel"


class RecoveryEdge(ContractModel):
    trigger: RecoveryTrigger
    guard: dict[str, Any] = Field(
        default_factory=dict,
        description="context predicates: list value = membership, scalar = equality; missing key = no match",
    )
    target: RecoveryBehavior
    then: RecoveryBehavior | None = Field(default=None, description="follow-up behaviour after `after_s`")
    after_s: float | None = Field(default=None, gt=0)
    fault_injection_scenario: str | None = Field(default=None, description="scenario id that verified this edge")

    @model_validator(mode="after")
    def _then_needs_delay(self) -> RecoveryEdge:
        if (self.then is None) != (self.after_s is None):
            raise ValueError("`then` and `after_s` must be given together")
        return self

    def matches(self, trigger: RecoveryTrigger, context: dict[str, Any]) -> bool:
        if trigger is not self.trigger:
            return False
        for key, expected in self.guard.items():
            if key not in context:
                return False
            actual = context[key]
            if isinstance(expected, list):
                if actual not in expected:
                    return False
            elif actual != expected:
                return False
        return True


class RecoveryPolicy(ContractModel):
    policy_id: str
    version: str
    embodiment: Embodiment
    nodes: set[RecoveryBehavior]
    edges: list[RecoveryEdge]
    resume_conditions: list[str] = Field(
        default_factory=list,
        description="all must hold before control returns to the high-performance path",
    )

    @model_validator(mode="after")
    def _edges_reference_nodes(self) -> RecoveryPolicy:
        for e in self.edges:
            for b in (e.target, e.then):
                if b is not None and b not in self.nodes:
                    raise ValueError(f"edge for {e.trigger.value} targets {b.value}, which is not a policy node")
        return self

    def validate_against(self, caps: CapabilityDescriptor) -> list[str]:
        """Errors that make this policy unusable on the given platform."""
        errors: list[str] = []
        if caps.embodiment is not self.embodiment:
            errors.append(f"embodiment mismatch: policy {self.embodiment.value}, robot {caps.embodiment.value}")
        unsupported = sorted(b.value for b in self.nodes if b not in caps.recovery_behaviors)
        if unsupported:
            errors.append(f"behaviours not supported by platform: {unsupported}")
        if not caps.limits.can_hover and RecoveryBehavior.HOLD in self.nodes:
            errors.append("platform cannot hover; use loiter instead of hold")
        return errors

    def unverified_edges(self) -> list[RecoveryEdge]:
        return [e for e in self.edges if not e.fault_injection_scenario]

    def select(self, trigger: RecoveryTrigger, context: dict[str, Any]) -> RecoveryEdge | None:
        """First matching edge wins; order edges from most specific to least specific."""
        for e in self.edges:
            if e.matches(trigger, context):
                return e
        return None

    @classmethod
    def from_yaml(cls, path: str | Path) -> RecoveryPolicy:
        data = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        return cls.model_validate(data)
