"""Export the model inventory and shared wire draft; reject accidental renumbering.

导出模型字段清单与共享 wire 草案；拒绝意外重编号。
"""

from __future__ import annotations

import argparse
import inspect
import json
import re
from datetime import datetime
from enum import Enum
from pathlib import Path
from types import UnionType
from typing import Annotated, Any, Union, get_args, get_origin

import drone_agent.contracts as contracts
from drone_agent.contracts import CONTRACT_VERSION, ContractModel

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "proto/contract-fields.json"
SHARED_PROTO = ROOT / "proto/drone/contracts/v1/contracts.proto"
MODELS = {
    name: obj
    for name, obj in inspect.getmembers(contracts, inspect.isclass)
    if issubclass(obj, ContractModel) and obj is not ContractModel
}
ENUMS = {
    name: obj for name, obj in inspect.getmembers(contracts, inspect.isclass) if issubclass(obj, Enum)
}


def enum_prefix(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def wire_type(annotation: Any) -> tuple[str, str]:
    """Map typed containers and scalars; free JSON stays lossless UTF-8 bytes.

    映射定型容器与标量；自由 JSON 保持为无损 UTF-8 字节。
    """
    origin, args = get_origin(annotation), get_args(annotation)
    if origin is Annotated:
        return wire_type(args[0])
    if origin in (Union, UnionType):
        members = [arg for arg in args if arg is not type(None)]
        if len(members) != 1:
            raise TypeError(f"unsupported union: {annotation}")
        return wire_type(members[0])
    if origin in (list, set, tuple, frozenset):
        _, item = wire_type(args[0])
        return "repeated", item
    if origin is dict or annotation is Any:
        return "optional", "bytes"
    scalars = {str: "string", int: "int64", float: "double", bool: "bool", datetime: "google.protobuf.Timestamp"}
    if annotation in scalars:
        return "optional", scalars[annotation]
    if inspect.isclass(annotation) and issubclass(annotation, (ContractModel, Enum)):
        return "optional", annotation.__name__
    # Pydantic's timezone-aware datetime annotates the same Timestamp wire type.
    # Pydantic 带时区 datetime 与普通 datetime 使用相同的 Timestamp wire 类型。
    if getattr(annotation, "__name__", "") == "AwareDatetime":
        return "optional", "google.protobuf.Timestamp"
    raise TypeError(f"unsupported annotation: {annotation}")


def build_inventory() -> dict:
    result = {"schema_version": CONTRACT_VERSION, "models": {}, "enums": {}}
    for name, model in MODELS.items():
        schema = model.model_json_schema()
        result["models"][name] = [
            {
                "name": field_name,
                "number": index,
                "required": field.is_required(),
                "cardinality": wire_type(field.annotation)[0],
                "wire_type": wire_type(field.annotation)[1],
                "schema": schema["properties"][field_name],
            }
            for index, (field_name, field) in enumerate(model.model_fields.items(), start=1)
        ]
    for name, enum in ENUMS.items():
        result["enums"][name] = {f"{enum_prefix(name)}_UNSPECIFIED": 0} | {
            f"{enum_prefix(name)}_{member.name}": index for index, member in enumerate(enum, start=1)
        }
    return result


def render_proto(inventory: dict) -> str:
    lines = [
        '// Generated by scripts/generate_contract_fields.py; review before freezing v1.',
        '// 由 scripts/generate_contract_fields.py 生成；冻结 v1 前必须审查。',
        'syntax = "proto3";',
        'package drone.contracts.v1;',
        'import "google/protobuf/timestamp.proto";',
        '',
    ]
    for name, values in inventory["enums"].items():
        lines.append(f"enum {name} {{")
        lines.extend(f"  {key} = {value};" for key, value in values.items())
        lines.extend(["}", ""])
    for name, fields in inventory["models"].items():
        lines.append(f"message {name} {{")
        for field in fields:
            if field["wire_type"] == "bytes":
                lines.append("  // UTF-8 JSON; validate after decoding. / UTF-8 JSON；解码后重新校验。")
            lines.append(
                f"  {field['cardinality']} {field['wire_type']} {field['name']} = {field['number']};"
            )
        lines.extend(["}", ""])
    return "\n".join(lines)


def check_compatibility(previous: dict, current: dict) -> None:
    """M0 additions must retain every published field number and wire type.

    M0 增量修改必须保留已记录的每个字段号与 wire 类型。
    """
    for name, old_fields in previous["models"].items():
        new_fields = {field["name"]: field for field in current["models"].get(name, [])}
        for field in old_fields:
            new = new_fields.get(field["name"])
            if new is None or any(new[key] != field[key] for key in ("number", "wire_type", "cardinality")):
                raise ValueError(f"breaking wire change: {name}.{field['name']}; review a new major version")
    for name, values in previous["enums"].items():
        if any(current["enums"].get(name, {}).get(key) != number for key, number in values.items()):
            raise ValueError(f"breaking enum change: {name}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    inventory = build_inventory()
    outputs = {
        INVENTORY: json.dumps(inventory, ensure_ascii=False, indent=2) + "\n",
        SHARED_PROTO: render_proto(inventory),
    }
    if INVENTORY.exists():
        check_compatibility(json.loads(INVENTORY.read_text(encoding="utf-8")), inventory)
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"stale contract artifact: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    print(f"{len(MODELS)} models, {sum(len(v) for v in inventory['models'].values())} fields, {len(ENUMS)} enums")


if __name__ == "__main__":
    main()
